# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def run
  fib = []
  x = 1
  while x <= 4000000
    fib << x
    if x > 2
      i = fib.find_index(x)
      x = fib[i] + fib[i-1]
    else
      x += 1
    end
  end
  fib.inject(0){|sum, num| num % 2 == 0 ? sum += num : sum}
end
