// Even Fibonacci numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function run() {
  var
    fibs = [],
    x = 1,
    sum = 0;
  while(x <= 4000000) {
    fibs.push(x);
    if(x === 1) {
      x++;
    }
    else {
      x += fibs[fibs.length - 2];
    };
  };
  fibs.map(function(i) {
    if(i % 2 === 0) {
      sum += i;
    };
  });
  return sum;
};

// 4613732